// Generated by scripts/generate-clock-ticks.mjs from clockFace.json.
// Do not edit these coordinates by hand; run npm run clock:generate.

export interface TickPosition {
  index: number
  angleDeg: number
  isMajor: boolean
  x1: number
  y1: number
  x2: number
  y2: number
}

export const TICK_POSITIONS = [
  { index: 0, angleDeg: 0, isMajor: true, x1: 270, y1: 85, x2: 270, y2: 45 },
  { index: 1, angleDeg: 6, isMajor: false, x1: 291.01, y1: 70.101, x2: 293.519, y2: 46.233 },
  { index: 2, angleDeg: 12, isMajor: false, x1: 311.79, y1: 73.392, x2: 316.78, y2: 49.917 },
  { index: 3, angleDeg: 18, isMajor: false, x1: 332.112, y1: 78.838, x2: 339.529, y2: 56.012 },
  { index: 4, angleDeg: 24, isMajor: false, x1: 351.754, y1: 86.377, x2: 361.516, y2: 64.452 },
  { index: 5, angleDeg: 30, isMajor: true, x1: 362.5, y1: 109.785, x2: 382.5, y2: 75.144 },
  { index: 6, angleDeg: 36, isMajor: false, x1: 388.145, y1: 107.388, x2: 402.252, y2: 87.971 },
  { index: 7, angleDeg: 42, isMajor: false, x1: 404.495, y1: 120.628, x2: 420.554, y2: 102.792 },
  { index: 8, angleDeg: 48, isMajor: false, x1: 419.372, y1: 135.505, x2: 437.208, y2: 119.446 },
  { index: 9, angleDeg: 54, isMajor: false, x1: 432.612, y1: 151.855, x2: 452.029, y2: 137.748 },
  { index: 10, angleDeg: 60, isMajor: true, x1: 430.215, y1: 177.5, x2: 464.856, y2: 157.5 },
  { index: 11, angleDeg: 66, isMajor: false, x1: 453.623, y1: 188.246, x2: 475.548, y2: 178.484 },
  { index: 12, angleDeg: 72, isMajor: false, x1: 461.162, y1: 207.888, x2: 483.988, y2: 200.471 },
  { index: 13, angleDeg: 78, isMajor: false, x1: 466.608, y1: 228.21, x2: 490.083, y2: 223.22 },
  { index: 14, angleDeg: 84, isMajor: false, x1: 469.899, y1: 248.99, x2: 493.767, y2: 246.481 },
  { index: 15, angleDeg: 90, isMajor: true, x1: 455, y1: 270, x2: 495, y2: 270 },
  { index: 16, angleDeg: 96, isMajor: false, x1: 469.899, y1: 291.01, x2: 493.767, y2: 293.519 },
  { index: 17, angleDeg: 102, isMajor: false, x1: 466.608, y1: 311.79, x2: 490.083, y2: 316.78 },
  { index: 18, angleDeg: 108, isMajor: false, x1: 461.162, y1: 332.112, x2: 483.988, y2: 339.529 },
  { index: 19, angleDeg: 114, isMajor: false, x1: 453.623, y1: 351.754, x2: 475.548, y2: 361.516 },
  { index: 20, angleDeg: 120, isMajor: true, x1: 430.215, y1: 362.5, x2: 464.856, y2: 382.5 },
  { index: 21, angleDeg: 126, isMajor: false, x1: 432.612, y1: 388.145, x2: 452.029, y2: 402.252 },
  { index: 22, angleDeg: 132, isMajor: false, x1: 419.372, y1: 404.495, x2: 437.208, y2: 420.554 },
  { index: 23, angleDeg: 138, isMajor: false, x1: 404.495, y1: 419.372, x2: 420.554, y2: 437.208 },
  { index: 24, angleDeg: 144, isMajor: false, x1: 388.145, y1: 432.612, x2: 402.252, y2: 452.029 },
  { index: 25, angleDeg: 150, isMajor: true, x1: 362.5, y1: 430.215, x2: 382.5, y2: 464.856 },
  { index: 26, angleDeg: 156, isMajor: false, x1: 351.754, y1: 453.623, x2: 361.516, y2: 475.548 },
  { index: 27, angleDeg: 162, isMajor: false, x1: 332.112, y1: 461.162, x2: 339.529, y2: 483.988 },
  { index: 28, angleDeg: 168, isMajor: false, x1: 311.79, y1: 466.608, x2: 316.78, y2: 490.083 },
  { index: 29, angleDeg: 174, isMajor: false, x1: 291.01, y1: 469.899, x2: 293.519, y2: 493.767 },
  { index: 30, angleDeg: 180, isMajor: true, x1: 270, y1: 455, x2: 270, y2: 495 },
  { index: 31, angleDeg: 186, isMajor: false, x1: 248.99, y1: 469.899, x2: 246.481, y2: 493.767 },
  { index: 32, angleDeg: 192, isMajor: false, x1: 228.21, y1: 466.608, x2: 223.22, y2: 490.083 },
  { index: 33, angleDeg: 198, isMajor: false, x1: 207.888, y1: 461.162, x2: 200.471, y2: 483.988 },
  { index: 34, angleDeg: 204, isMajor: false, x1: 188.246, y1: 453.623, x2: 178.484, y2: 475.548 },
  { index: 35, angleDeg: 210, isMajor: true, x1: 177.5, y1: 430.215, x2: 157.5, y2: 464.856 },
  { index: 36, angleDeg: 216, isMajor: false, x1: 151.855, y1: 432.612, x2: 137.748, y2: 452.029 },
  { index: 37, angleDeg: 222, isMajor: false, x1: 135.505, y1: 419.372, x2: 119.446, y2: 437.208 },
  { index: 38, angleDeg: 228, isMajor: false, x1: 120.628, y1: 404.495, x2: 102.792, y2: 420.554 },
  { index: 39, angleDeg: 234, isMajor: false, x1: 107.388, y1: 388.145, x2: 87.971, y2: 402.252 },
  { index: 40, angleDeg: 240, isMajor: true, x1: 109.785, y1: 362.5, x2: 75.144, y2: 382.5 },
  { index: 41, angleDeg: 246, isMajor: false, x1: 86.377, y1: 351.754, x2: 64.452, y2: 361.516 },
  { index: 42, angleDeg: 252, isMajor: false, x1: 78.838, y1: 332.112, x2: 56.012, y2: 339.529 },
  { index: 43, angleDeg: 258, isMajor: false, x1: 73.392, y1: 311.79, x2: 49.917, y2: 316.78 },
  { index: 44, angleDeg: 264, isMajor: false, x1: 70.101, y1: 291.01, x2: 46.233, y2: 293.519 },
  { index: 45, angleDeg: 270, isMajor: true, x1: 85, y1: 270, x2: 45, y2: 270 },
  { index: 46, angleDeg: 276, isMajor: false, x1: 70.101, y1: 248.99, x2: 46.233, y2: 246.481 },
  { index: 47, angleDeg: 282, isMajor: false, x1: 73.392, y1: 228.21, x2: 49.917, y2: 223.22 },
  { index: 48, angleDeg: 288, isMajor: false, x1: 78.838, y1: 207.888, x2: 56.012, y2: 200.471 },
  { index: 49, angleDeg: 294, isMajor: false, x1: 86.377, y1: 188.246, x2: 64.452, y2: 178.484 },
  { index: 50, angleDeg: 300, isMajor: true, x1: 109.785, y1: 177.5, x2: 75.144, y2: 157.5 },
  { index: 51, angleDeg: 306, isMajor: false, x1: 107.388, y1: 151.855, x2: 87.971, y2: 137.748 },
  { index: 52, angleDeg: 312, isMajor: false, x1: 120.628, y1: 135.505, x2: 102.792, y2: 119.446 },
  { index: 53, angleDeg: 318, isMajor: false, x1: 135.505, y1: 120.628, x2: 119.446, y2: 102.792 },
  { index: 54, angleDeg: 324, isMajor: false, x1: 151.855, y1: 107.388, x2: 137.748, y2: 87.971 },
  { index: 55, angleDeg: 330, isMajor: true, x1: 177.5, y1: 109.785, x2: 157.5, y2: 75.144 },
  { index: 56, angleDeg: 336, isMajor: false, x1: 188.246, y1: 86.377, x2: 178.484, y2: 64.452 },
  { index: 57, angleDeg: 342, isMajor: false, x1: 207.888, y1: 78.838, x2: 200.471, y2: 56.012 },
  { index: 58, angleDeg: 348, isMajor: false, x1: 228.21, y1: 73.392, x2: 223.22, y2: 49.917 },
  { index: 59, angleDeg: 354, isMajor: false, x1: 248.99, y1: 70.101, x2: 246.481, y2: 46.233 }
] as const satisfies readonly TickPosition[]
