// Generated by scripts/generate-clock-ticks.mjs from clockFace.json.
// Do not edit these coordinates by hand; run npm run clock:generate.

export interface TickPosition {
  index: number
  angleDeg: number
  isMajor: boolean
  x1: number
  y1: number
  x2: number
  y2: number
}

export const TICK_POSITIONS = [
  { index: 0, angleDeg: 0, isMajor: true, x1: 270, y1: 58, x2: 270, y2: 18 },
  { index: 1, angleDeg: 6, isMajor: false, x1: 293.832, y1: 43.249, x2: 296.341, y2: 19.38 },
  { index: 2, angleDeg: 12, isMajor: false, x1: 317.404, y1: 46.982, x2: 322.394, y2: 23.507 },
  { index: 3, angleDeg: 18, isMajor: false, x1: 340.456, y1: 53.159, x2: 347.872, y2: 30.334 },
  { index: 4, angleDeg: 24, isMajor: false, x1: 362.736, y1: 61.712, x2: 372.498, y2: 39.787 },
  { index: 5, angleDeg: 30, isMajor: true, x1: 376, y1: 86.403, x2: 396, y2: 51.762 },
  { index: 6, angleDeg: 36, isMajor: false, x1: 404.015, y1: 85.544, x2: 418.122, y2: 66.128 },
  { index: 7, angleDeg: 42, isMajor: false, x1: 422.562, y1: 100.563, x2: 438.621, y2: 82.728 },
  { index: 8, angleDeg: 48, isMajor: false, x1: 439.437, y1: 117.438, x2: 457.272, y2: 101.379 },
  { index: 9, angleDeg: 54, isMajor: false, x1: 454.456, y1: 135.985, x2: 473.872, y2: 121.878 },
  { index: 10, angleDeg: 60, isMajor: true, x1: 453.597, y1: 164, x2: 488.238, y2: 144 },
  { index: 11, angleDeg: 66, isMajor: false, x1: 478.288, y1: 177.264, x2: 500.213, y2: 167.502 },
  { index: 12, angleDeg: 72, isMajor: false, x1: 486.841, y1: 199.544, x2: 509.666, y2: 192.128 },
  { index: 13, angleDeg: 78, isMajor: false, x1: 493.018, y1: 222.596, x2: 516.493, y2: 217.606 },
  { index: 14, angleDeg: 84, isMajor: false, x1: 496.751, y1: 246.168, x2: 520.62, y2: 243.659 },
  { index: 15, angleDeg: 90, isMajor: true, x1: 482, y1: 270, x2: 522, y2: 270 },
  { index: 16, angleDeg: 96, isMajor: false, x1: 496.751, y1: 293.832, x2: 520.62, y2: 296.341 },
  { index: 17, angleDeg: 102, isMajor: false, x1: 493.018, y1: 317.404, x2: 516.493, y2: 322.394 },
  { index: 18, angleDeg: 108, isMajor: false, x1: 486.841, y1: 340.456, x2: 509.666, y2: 347.872 },
  { index: 19, angleDeg: 114, isMajor: false, x1: 478.288, y1: 362.736, x2: 500.213, y2: 372.498 },
  { index: 20, angleDeg: 120, isMajor: true, x1: 453.597, y1: 376, x2: 488.238, y2: 396 },
  { index: 21, angleDeg: 126, isMajor: false, x1: 454.456, y1: 404.015, x2: 473.872, y2: 418.122 },
  { index: 22, angleDeg: 132, isMajor: false, x1: 439.437, y1: 422.562, x2: 457.272, y2: 438.621 },
  { index: 23, angleDeg: 138, isMajor: false, x1: 422.562, y1: 439.437, x2: 438.621, y2: 457.272 },
  { index: 24, angleDeg: 144, isMajor: false, x1: 404.015, y1: 454.456, x2: 418.122, y2: 473.872 },
  { index: 25, angleDeg: 150, isMajor: true, x1: 376, y1: 453.597, x2: 396, y2: 488.238 },
  { index: 26, angleDeg: 156, isMajor: false, x1: 362.736, y1: 478.288, x2: 372.498, y2: 500.213 },
  { index: 27, angleDeg: 162, isMajor: false, x1: 340.456, y1: 486.841, x2: 347.872, y2: 509.666 },
  { index: 28, angleDeg: 168, isMajor: false, x1: 317.404, y1: 493.018, x2: 322.394, y2: 516.493 },
  { index: 29, angleDeg: 174, isMajor: false, x1: 293.832, y1: 496.751, x2: 296.341, y2: 520.62 },
  { index: 30, angleDeg: 180, isMajor: true, x1: 270, y1: 482, x2: 270, y2: 522 },
  { index: 31, angleDeg: 186, isMajor: false, x1: 246.168, y1: 496.751, x2: 243.659, y2: 520.62 },
  { index: 32, angleDeg: 192, isMajor: false, x1: 222.596, y1: 493.018, x2: 217.606, y2: 516.493 },
  { index: 33, angleDeg: 198, isMajor: false, x1: 199.544, y1: 486.841, x2: 192.128, y2: 509.666 },
  { index: 34, angleDeg: 204, isMajor: false, x1: 177.264, y1: 478.288, x2: 167.502, y2: 500.213 },
  { index: 35, angleDeg: 210, isMajor: true, x1: 164, y1: 453.597, x2: 144, y2: 488.238 },
  { index: 36, angleDeg: 216, isMajor: false, x1: 135.985, y1: 454.456, x2: 121.878, y2: 473.872 },
  { index: 37, angleDeg: 222, isMajor: false, x1: 117.438, y1: 439.437, x2: 101.379, y2: 457.272 },
  { index: 38, angleDeg: 228, isMajor: false, x1: 100.563, y1: 422.562, x2: 82.728, y2: 438.621 },
  { index: 39, angleDeg: 234, isMajor: false, x1: 85.544, y1: 404.015, x2: 66.128, y2: 418.122 },
  { index: 40, angleDeg: 240, isMajor: true, x1: 86.403, y1: 376, x2: 51.762, y2: 396 },
  { index: 41, angleDeg: 246, isMajor: false, x1: 61.712, y1: 362.736, x2: 39.787, y2: 372.498 },
  { index: 42, angleDeg: 252, isMajor: false, x1: 53.159, y1: 340.456, x2: 30.334, y2: 347.872 },
  { index: 43, angleDeg: 258, isMajor: false, x1: 46.982, y1: 317.404, x2: 23.507, y2: 322.394 },
  { index: 44, angleDeg: 264, isMajor: false, x1: 43.249, y1: 293.832, x2: 19.38, y2: 296.341 },
  { index: 45, angleDeg: 270, isMajor: true, x1: 58, y1: 270, x2: 18, y2: 270 },
  { index: 46, angleDeg: 276, isMajor: false, x1: 43.249, y1: 246.168, x2: 19.38, y2: 243.659 },
  { index: 47, angleDeg: 282, isMajor: false, x1: 46.982, y1: 222.596, x2: 23.507, y2: 217.606 },
  { index: 48, angleDeg: 288, isMajor: false, x1: 53.159, y1: 199.544, x2: 30.334, y2: 192.128 },
  { index: 49, angleDeg: 294, isMajor: false, x1: 61.712, y1: 177.264, x2: 39.787, y2: 167.502 },
  { index: 50, angleDeg: 300, isMajor: true, x1: 86.403, y1: 164, x2: 51.762, y2: 144 },
  { index: 51, angleDeg: 306, isMajor: false, x1: 85.544, y1: 135.985, x2: 66.128, y2: 121.878 },
  { index: 52, angleDeg: 312, isMajor: false, x1: 100.563, y1: 117.438, x2: 82.728, y2: 101.379 },
  { index: 53, angleDeg: 318, isMajor: false, x1: 117.438, y1: 100.563, x2: 101.379, y2: 82.728 },
  { index: 54, angleDeg: 324, isMajor: false, x1: 135.985, y1: 85.544, x2: 121.878, y2: 66.128 },
  { index: 55, angleDeg: 330, isMajor: true, x1: 164, y1: 86.403, x2: 144, y2: 51.762 },
  { index: 56, angleDeg: 336, isMajor: false, x1: 177.264, y1: 61.712, x2: 167.502, y2: 39.787 },
  { index: 57, angleDeg: 342, isMajor: false, x1: 199.544, y1: 53.159, x2: 192.128, y2: 30.334 },
  { index: 58, angleDeg: 348, isMajor: false, x1: 222.596, y1: 46.982, x2: 217.606, y2: 23.507 },
  { index: 59, angleDeg: 354, isMajor: false, x1: 246.168, y1: 43.249, x2: 243.659, y2: 19.38 }
] as const satisfies readonly TickPosition[]
